package Vistas;

import Controladores.PacientesController;
import ControladoresJPA.exceptions.NonexistentEntityException;
import Modelo.Paciente;
import Vistas.modelos.PacienteTableModel;
import clinica.Controladores;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class PacienteUI extends javax.swing.JPanel {

    private PacientesController controlador;
    /**
     * Creates new form PacienteUI
     */
    public PacienteUI() {
        initComponents();
        controlador = Controladores.pacientesController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        etiquetaDni = new javax.swing.JLabel();
        etiquetaApellido = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaDireccion = new javax.swing.JLabel();
        etiquetaTelefono = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoDomicilio = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonEliminarPaciente = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        campoDni = new javax.swing.JSpinner();
        botonHistorial = new javax.swing.JButton();
        jpPacientes = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Pacientes");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        jpDatos.setMaximumSize(new java.awt.Dimension(275, 465));
        jpDatos.setMinimumSize(new java.awt.Dimension(275, 465));

        etiquetaDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaDni.setText("DNI");

        etiquetaApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaApellido.setText("Apellido");

        etiquetaNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaNombre.setText("Nombre");

        etiquetaDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaDireccion.setText("Domicilio");

        etiquetaTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaTelefono.setText("Teléfono");
        etiquetaTelefono.setName("");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonEliminarPaciente.setText("Eliminar Paciente");
        botonEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPacienteActionPerformed(evt);
            }
        });

        separador.setMaximumSize(new java.awt.Dimension(50, 10));

        botonHistorial.setText("Ver Historial");
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDni)
                                    .addComponent(etiquetaApellido)
                                    .addComponent(etiquetaNombre)
                                    .addComponent(etiquetaDireccion)
                                    .addComponent(etiquetaTelefono))
                                .addGap(30, 30, 30)
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(campoDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(campoDni)))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(botonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar))))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonEliminarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(botonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDni)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellido)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDireccion)
                    .addComponent(campoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTelefono)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarPaciente)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        add(jpDatos, java.awt.BorderLayout.LINE_END);

        tablaPacientes.setModel(new Vistas.modelos.PacienteTableModel());
        tablaPacientes.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaPacientes);

        javax.swing.GroupLayout jpPacientesLayout = new javax.swing.GroupLayout(jpPacientes);
        jpPacientes.setLayout(jpPacientesLayout);
        jpPacientesLayout.setHorizontalGroup(
            jpPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        jpPacientesLayout.setVerticalGroup(
            jpPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        add(jpPacientes, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        Paciente p = new Paciente();
        p.setDni((Long)campoDni.getValue());
        p.setApellido(campoApellido.getText());
        p.setNombre(campoNombre.getText());
        p.setDomicilio(campoDomicilio.getText());
        p.setTelefono(campoTelefono.getText());
        controlador.registrarNuevoPaciente(p);
        limpiarCampos();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPacienteActionPerformed
        try {
            int[] filas = tablaPacientes.getSelectedRows();
            if(filas.length > 0) {
                PacienteTableModel modelo = (PacienteTableModel)tablaPacientes.getModel();
                for(int i : filas)
                    controlador.eliminarPaciente(modelo.obtenerPaciente(i));
            }
            else
                throw new Exception("No ha seleccionado ningun paciente");
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarPacienteActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonHistorialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminarPaciente;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JSpinner campoDni;
    private javax.swing.JTextField campoDomicilio;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaDni;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpPacientes;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoDni.setValue(0);
        campoApellido.setText("");
        campoNombre.setText("");
        campoDomicilio.setText("");
        campoTelefono.setText("");
    }

}
